"""Offline feature-support diagnostics: old TRAIN versus online decision X.

No labels are mixed, no checkpoint is fitted, no force/utility is changed.
"""
import argparse
import json
from pathlib import Path
import numpy as np
from common import BASE, HERE, read, sha

KEEP = list(range(6))+list(range(13,71))


def review(out):
    out = Path(out)
    stage = read(BASE/'current_matched_stage1_648_v1_20260906/STAGE_MANIFEST.json')
    metadata = {p['id']:p for p in stage['contexts']}
    groups = {'TRAIN': [], 'VAL': [], 'TEST': []}
    hashes = {}
    for p in sorted((BASE/'current_matched_resumption_v1_20260906/rows').glob('*.json')):
        row = read(p); cid = row['context_id']
        split = stage['split_by_context'][cid]
        x = np.load(Path(row['job'])/'PREACTION_SEQUENCE.npy').astype(np.float32)[:,KEEP]
        x[:,10] = row['force']/8; x[:,11] = metadata[cid]['mu']
        groups[split].append(x); hashes[str(p)] = sha(p)
    if sum(map(len,groups.values())) != 647:
        raise RuntimeError('Require exact audited old647 rows')
    train = np.stack(groups['TRAIN']).reshape(-1,64)
    old_all = np.concatenate([np.stack(x).reshape(-1,64) for x in groups.values()])
    mf = read(BASE/'current_fulltask_feasibility_runtime_freeze_v2_20260906/FINAL_FEASIBILITY_RUNTIME_MANIFEST.json')
    mean = np.asarray(mf['normalization']['mean'])[KEEP]
    std = np.asarray(mf['normalization']['std'])[KEEP]
    lo, hi = train.min(0), train.max(0)
    schema = read(HERE/'FEASIBILITY_FEATURE_SCHEMA_AUDIT.json')['FINAL_CANDIDATE_FEATURE_RECORDS']
    names = {r['FEATURE_INDEX']:r['FEATURE_NAME'] for r in schema}
    rows = []
    for p in sorted((out/'branches').glob('*__ACTIVEFORCING/PROCESS_EXIT.json')):
        if read(p)['exit_code'] != 0:
            raise RuntimeError('Invalid completed worker')
        job = p.parent; x = np.load(job/'PREACTION_SEQUENCE.npy')
        d = read(job/'PLANNER_DECISION.json'); post = read(job/'PREACTION_POSTERIOR.json')
        if x.shape != (8,64):
            raise RuntimeError('Require phase-free online schema')
        # F and mu placeholders in the saved base are not observations.
        # Report selected-force support and quadrature mass separately.
        features = []
        for i in range(64):
            if i in (10,11):
                continue
            values = x[:,i] if i < 10 else x[:1,i]
            features.append(dict(index=i,name=names[i],train_min=float(lo[i]),train_max=float(hi[i]),
                all647_min=float(old_all[:,i].min()),all647_max=float(old_all[:,i].max()),
                online_min=float(values.min()),online_max=float(values.max()),
                outside_train_range=bool(np.any((values<lo[i]-1e-6)|(values>hi[i]+1e-6))),
                maximum_abs_train_normalized=float(np.max(abs((values-mean[i])/std[i])))))
        nodes = np.asarray(post['integration_nodes']); weights = np.asarray(post['integration_weights'])
        rows.append(dict(context=read(job/'BRANCH_RESULT.json')['plan']['id'], features=features,
            selected_force_N=d['executed_force_N'],
            selected_force_inside_train_support=bool(lo[10]-1e-6<=d['executed_force_N']/8<=hi[10]+1e-6),
            posterior_mass_outside_train_mu_range=float(weights[(nodes<lo[11])|(nodes>hi[11])].sum()),
            posterior_mass_outside_all647_mu_range=float(weights[(nodes<old_all[:,11].min())|(nodes>old_all[:,11].max())].sum()),
            preaction_sequence_sha256=sha(job/'PREACTION_SEQUENCE.npy'),posterior_sha256=sha(job/'PREACTION_POSTERIOR.json')))
    return dict(role='OFFLINE_SUPPORT_DIAGNOSTIC_NOT_TRANSFER_VERDICT', old_rows_by_split={k:len(v) for k,v in groups.items()},
        online_contexts=len(rows), rows=rows,
        feature_indices_outside_train_in_any_context=sorted({f['index'] for r in rows for f in r['features'] if f['outside_train_range']}),
        old_row_hashes=hashes, normalization_manifest_sha256=sha(BASE/'current_fulltask_feasibility_runtime_freeze_v2_20260906/FINAL_FEASIBILITY_RUNTIME_MANIFEST.json'),
        interpretations=[
            'Online chunk motion was nearly absent in scripted647; raw range extrapolation must be disclosed even if model probability/force qualification succeeds.',
            'Per-channel range membership is not joint feature support or proof of behavioral validity.',
            'Quadrature mu is a latent integration variable, not hidden runtime material friction. Report out-of-training mass rather than treating placeholder zero as an observation.',
            'No outcome labels or physical experiments are generated by this diagnostic.',
        ])


if __name__ == '__main__':
    p = argparse.ArgumentParser();p.add_argument('out');p.add_argument('--save',required=True);a=p.parse_args()
    d = review(a.out);Path(a.save).write_text(json.dumps(d,indent=2)+'\n')
    print(json.dumps({k:d[k] for k in ('online_contexts','old_rows_by_split','feature_indices_outside_train_in_any_context')},indent=2))
