from pathlib import Path
import json,csv,hashlib,collections,numpy as np
OUT=Path('/media/volume/newdata/exouser/online_vla_activeforcing_20260907/confirmatory_v1')
def readj(p):return json.loads(Path(p).read_text())
def writej(p,x):Path(p).write_text(json.dumps(x,indent=2,sort_keys=True,allow_nan=False)+'\n')
def csvread(p):return list(csv.DictReader(Path(p).open()))
def mean(x):return float(np.mean(x))
status=readj(OUT/'FINAL_CONFIRMATORY_STATUS.json'); nr=status['NEW4_ROOT_RESULTS']; pr=status['POOLED8_ROOT_RESULTS']; new=status['NEW4_RESULTS']; pool=status['POOLED8_RESULTS']; paired=status['PAIRED_NEW4']; fail=status['FAILURE_COUNTS']; diag=status['DIAGNOSIS_COUNTS']
force=[float(x['AF_minus_F5_force_saving']) for x in nr]; succ=[float(x['AF_minus_F5_SR_difference']) for x in nr]
status.update({'NEW4_REPLICATES_PREVIOUS_TREND':'MIXED','NEW4_FORCE_SAVING_DIRECTION_ALL_ROOTS':all(x>0 for x in force),'NEW4_SUCCESS_DIFFERENCE_VS_F5_PER_ROOT':succ,'NEW4_FORCE_SAVING_VS_F5_PER_ROOT':force,'PAPER_FIXED5_RELIABILITY_CLAIM':'PARTIAL','REMAINING_BLOCKERS':[],'PHYSICS_STOPPED_AFTER_CONFIRMATORY_RUN':True,'FINAL_CONFIRMATORY_REPORT':'FINAL_CONFIRMATORY_REPORT.md'})
writej(OUT/'FINAL_CONFIRMATORY_STATUS.json',status)
# Compact, answer-first report.
lines=['# Final confirmatory online-VLA evaluation','',f"Runtime freeze: PASS. Manifest SHA256: `{(OUT/'FINAL_CONFIRMATORY_RUNTIME_MANIFEST_SHA256.txt').read_text().strip()}`.",f"New roots: 170044, 170045, 170046, 170047. All 192 confirmatory branches completed; all passed online-VLA provenance and geometry admission. No retry was used. Physics is now stopped.",'','## New four-root confirmatory table','', '| Method | Full-task | Lift | Drop | Mean selected (N) | Mean measured bilateral squeeze (N) | Saving vs Fixed-5 measured (N) |','|---|---:|---:|---:|---:|---:|---:|']
for m in ['FIXED_3','FIXED_4','FIXED_5','ACTIVEFORCING']:
 a=new[m]; save=new['FIXED_5']['mean_measured_bilateral_squeeze']-a['mean_measured_bilateral_squeeze'];lines.append(f"| {m} | {a['full_task_success_n']}/48 ({100*a['full_task_SR']:.1f}%) | {100*a['lift_SR']:.1f}% | {100*a['drop_rate']:.1f}% | {a['mean_selected_force']:.3f} | {a['mean_measured_bilateral_squeeze']:.3f} | {save:.3f} |")
lines += ['', '## Eight-root pooled descriptive table','', '| Method | Full-task | Lift | Drop | Mean selected (N) | Mean measured bilateral squeeze (N) | Saving vs Fixed-5 measured (N) |','|---|---:|---:|---:|---:|---:|---:|']
for m in ['FIXED_3','FIXED_4','FIXED_5','ACTIVEFORCING']:
 a=pool[m]; save=pool['FIXED_5']['mean_measured_bilateral_squeeze']-a['mean_measured_bilateral_squeeze'];lines.append(f"| {m} | {a['full_task_success_n']}/96 ({100*a['full_task_SR']:.1f}%) | {100*a['lift_SR']:.1f}% | {100*a['drop_rate']:.1f}% | {a['mean_selected_force']:.3f} | {a['mean_measured_bilateral_squeeze']:.3f} | {save:.3f} |")
lines += ['', '## Paired confirmatory results','',f"- AF vs Fixed-3: both success {paired['Fixed3']['both_success']}, AF-only {paired['Fixed3']['AF_only_success']}, baseline-only {paired['Fixed3']['baseline_only_success']}, both fail {paired['Fixed3']['both_fail']}.",f"- AF vs Fixed-4: both success {paired['Fixed4']['both_success']}, AF-only {paired['Fixed4']['AF_only_success']}, baseline-only {paired['Fixed4']['baseline_only_success']}, both fail {paired['Fixed4']['both_fail']}.",f"- AF vs Fixed-5: both success {paired['Fixed5']['both_success']}, AF-only {paired['Fixed5']['AF_only_success']}, baseline-only {paired['Fixed5']['baseline_only_success']}, both fail {paired['Fixed5']['both_fail']}; force saving in both-success contexts = {status['AF_FIXED5_BOTH_SUCCESS_FORCE_SAVING']:.3f} N.",'', '## Root consistency','',f"New-root AF measured-force saving versus Fixed-5: {', '.join(f'{x:.3f} N' for x in force)}; direction is positive in all four roots.",f"New-root AF–Fixed-5 success differences: {', '.join(f'{x:+.3f}' for x in succ)}; success direction is mixed, so this is not a replication of a uniform reliability advantage.",'','## Failure composition','',f"Among pooled AF-fail/Fixed-5-success contexts: {sum(fail.values())} total; post-lift geometric={fail.get('POST_LIFT_GEOMETRIC',0)}, under-force={fail.get('UNDER_FORCE',0)}, VLA execution={fail.get('VLA_EXECUTION',0)}, other={fail.get('OTHER',0)}.",f"Diagnosis labels: execution variance={diag.get('EXECUTION_VARIANCE',0)}, utility aggressive={diag.get('UTILITY_AGGRESSIVE',0)}, model error={diag.get('MODEL_ERROR',0)}.",'','## Scientific conclusion','', 'The new four roots reproduce the measured-force-saving direction in every root, but the success comparison with Fixed-5 is mixed. In the eight-root pooled descriptive evaluation, ActiveForcing achieves 69/96 full-task successes versus 71/96 for Fixed-5 while using 1.170 N less mean measured bilateral squeeze (24.9%). It improves over Fixed-4 in success count (69/96 versus 65/96) but has a similar measured force. The supported claim is a reliability–force trade-off on top of a frozen online VLA; Fixed-5 reliability is only partially matched, so non-inferiority or superiority should not be claimed.']
(OUT/'FINAL_CONFIRMATORY_REPORT.md').write_text('\n'.join(lines)+'\n')
print('wrote',OUT/'FINAL_CONFIRMATORY_REPORT.md')
