#!/usr/bin/env python3
"""Assemble final mass-extension report and reproducibility bundle."""
from __future__ import annotations
import argparse, csv, hashlib, json, os, subprocess
from pathlib import Path

def sha(path):
    h=hashlib.sha256();
    with path.open("rb") as f:
        for b in iter(lambda:f.read(1<<20),b""):h.update(b)
    return h.hexdigest()
def files(root): return sorted(p for p in root.rglob("*") if p.is_file() and "REPRODUCIBILITY_BUNDLE" not in p.parts)
def main():
    ap=argparse.ArgumentParser();ap.add_argument("--root",type=Path,required=True);ap.add_argument("--formal",type=Path,required=True);ap.add_argument("--fresh",type=Path,required=True);ap.add_argument("--joint",type=Path,required=True);a=ap.parse_args();root=a.root;tables=root/"PAPER_MASS_TABLES";figures=root/"PAPER_MASS_FIGURES";bundle=root/"REPRODUCIBILITY_BUNDLE";tables.mkdir(exist_ok=True);figures.mkdir(exist_ok=True);bundle.mkdir(exist_ok=True)
    status={"formal_dataset":(a.formal/"M3_TASK2_STRUCTURED_FORMAL_PROTOCOL.json").exists(),"fresh_e2e":(a.fresh/"MASS_FRESH_E2E_PROTOCOL.json").exists(),"joint_pilot":(a.joint/"JOINT_PHYSICS_PILOT_PROTOCOL.json").exists(),"qualified_mass_tasks":[2],"breadth_gate":"COMPLETE_NEGATIVE_RESULT_ONLY_ONE_TASK_QUALIFIED"}
    (root/"PAPER_MASS_CLAIMS.md").write_text("""# Paper mass claims\n\n1. The frozen P4-B contact-conditioned physical query carries mass information under fixed appearance, geometry, friction, and root-heldout evaluation.\n2. The task2 salad-dressing recovered long-transport/turning/acceleration structure is mass-sensitive: lift remains reachable while downstream transport and full-task outcomes vary with force and mass.\n3. On the formal paired task2 benchmark, ActiveForcing-Mass is evaluated as query-only mass identification plus frozen Direct force selection.\n4. No claim is made that the screened breadth set contains two or more qualified mass-sensitive task IDs: task0/1/3/5/6/7/8/9 were negative or query-invalid, and planned task families remain planned.\n5. Vision is not claimed as an identifier because RGB was retained as an artifact but not used in the reported identifier.\n6. The joint friction×mass result is diagnostic and cannot alter the friction-only or mass-only conclusions.\n""")
    readme="""# Mass extension reproducibility bundle\n\nThis bundle belongs to the isolated `activeforcing-mass` worktrees and does not modify the protected friction archive.\n\n## Fixed protocol\n\n- Query: frozen P4-B contact-conditioned shear.\n- Controller: frozen Direct force-setpoint law; force candidates 0.5, 1.0, 1.5, 2.5, 4.0 N.\n- Formal task: recovered task2 `salad_dressing_1`, path `LONG_TRANSPORT_TURNING_ACCELERATION_V1`.\n- Mass: 0.05, 0.10, 0.20 kg; friction fixed at 0.5.\n- Sibling force branches remain within root/mass/repeat groups.\n- Identifier fitting reads query history only; formal TEST outcomes are not used to fit.\n\n## Commands\n\n```bash\n/media/volume/newdata/exouser/tabero/env_isaaclab51/bin/python analyze_mass_formal.py --inputs <formal-dir> --out PAPER_MASS_TABLES\n/media/volume/newdata/exouser/tabero/env_isaaclab51/bin/python collect_mass_fresh_e2e.py --out <fresh-dir> --formal-train <formal-dir> --roots 8400 8401\n/media/volume/newdata/exouser/tabero/env_isaaclab51/bin/python analyze_mass_fresh_e2e.py --input <fresh-dir> --out PAPER_MASS_TABLES\n/media/volume/newdata/exouser/tabero/env_isaaclab51/bin/python analyze_joint_physics_pilot.py --input <joint-dir> --out <joint-dir>\n```\n\n`MANIFEST_SHA256.json` records the files and hashes present when this bundle was assembled.\n"""
    (bundle/"README.md").write_text(readme)
    (bundle/"ENVIRONMENT.txt").write_text("UTC assembly timestamp is recorded in MANIFEST_SHA256.json. IsaacLab Python: /media/volume/newdata/exouser/tabero/env_isaaclab51/bin/python\n")
    manifest={"status":status,"base_commits":{"tabero":"80ab3be","forte":"7f88d01"},"worktrees":["/home/exouser/Tabero_mass","/home/exouser/FORTE_mass"],"files":{str(p.relative_to(root)):sha(p) for p in files(root)}}
    (bundle/"MANIFEST_SHA256.json").write_text(json.dumps(manifest,indent=2)+"\n")
    report={"status":"MASS_EXTENSION_READY_FOR_PAPER","completion_classification":"COMPLETE_NEGATIVE_RESULT","paper_readiness":"MASS_EXTENSION_READY_FOR_PAPER_FOR_QUALIFIED_TASK2","breadth_gate":"NOT_MET: only task2 qualified; all other recovered candidates negative or query-invalid","qualified_tasks":[{"task_id":2,"name":"salad_dressing_1","structure":"LONG_TRANSPORT_TURNING_ACCELERATION_V1"}],"negative_breadth_tasks":[0,1,3,5,6,7,8,9],"planned_only_tasks":["L1","T1","P1"],"m0_m7":status,"protected_friction_line":"unchanged"}
    (root/"ACTIVEFORCING_MASS_FINAL_REPORT.md").write_text("# ActiveForcing mass and task-breadth extension\n\n## Final status\n\n**MASS_EXTENSION_READY_FOR_PAPER** with completion classification **COMPLETE_NEGATIVE_RESULT** for the breadth hypothesis: the mass-only scientific line is complete for one qualified task, while the requested two-task breadth gate was not met after screening all recovered candidates. The friction core line and its 720-branch archive remain protected and unchanged.\n\n## Evidence\n\n"+json.dumps(report,indent=2)+"\n\nDetailed tables are under `PAPER_MASS_TABLES/`; figures are under `PAPER_MASS_FIGURES/`; source/data hashes are under `REPRODUCIBILITY_BUNDLE/`.\n")
    (root/"FINAL_STATUS.json").write_text(json.dumps(report,indent=2)+"\n")
if __name__=="__main__":main()
